### ISSUE TITLE
Sample

### ISSUE THREAD

**Issue by ThomasPerraudin** [Nickersoft/push-fcm-plugin#1]
Could you provide a full functional sample (with index.html, etc.) ?

**Comment by Nickersoft** [comment]
A full tutorial is going to be released soon in Net Magazine (ideally). However, until then, you can take a look at the demo repo I set up for that tutorial: https://github.com/Nickersoft/push-net-tutorial. A couple things to keep in mind with the demo though: all of my Firebase creds have been removed for privacy, so you'll have to fill that in with your own info. Additionally, Push and the FCM plugin are just in the base directory.. if you install via NPM or Bower, you'll want to make sure that the service worker files in the `bin` directories of those packages are accessible from the root of your server, in order to provide them global scope (so like https://example.com/serviceWorker.min.js). Also, you gotta use SSL on your site I believe.

**Comment by ThomasPerraudin** [comment]
Thank you that's a useful tutorial script. Althought I still encounter an error "Please ensure that 'messagingSenderId' is set correctly" although it is set ... I'm investigating.

**Comment by Nickersoft** [comment]
Are you just trying to run the code from that repo? As I said, it's missing configuration values.

**Comment by ThomasPerraudin** [comment]
Of course I updated the configuration with my values :-)

**Comment by Nickersoft** [comment]
And you're still getting an error?

**Comment by ThomasPerraudin** [comment]
It works ! Actually I had a technical problem with my editor. Everything works nicely. Thanks a lot for this very useful Push.js
