### ISSUE TITLE
location of mainifest file

### ISSUE THREAD

**Issue by norcross** [Nickersoft/push-fcm-plugin#7]
Is it possible to change the location, similar to the `serviceWorkerLocation`? Or just simply loading it in the HTML with whatever path it has work?

(I'm building this into a WordPress site and can't access the root directly)

**Comment by Nickersoft** [comment]
Hey @norcross, not sure if you ever figured this out, but the HTML `<link>` path should be fine (see the README). `manifest.json` is a Firebase thing, and Push doesn't need to know the location of it in order to run, as long as Firebase knows where it is. Read more [here](https://developers.google.com/web/fundamentals/web-app-manifest/).

**Comment by norcross** [comment]
I had actually got sidetracked on a different project, so this is timely. thanks!
